sonar.projectKey=Rubenpombo_end-to-end-data-pipeline
sonar.organization=rubenpombo
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**, .venv/**, tests/**
sonar.test.inclusions=tests/**
