apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    isDefault: true
    jsonData:
      keyspace: spark_streams
      consistency: ONE
    editable: true
