{
 "title": "User Registration Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "rawQuery": "SELECT id FROM created_users" }
   ]
  },
  {
   "title": "Gender Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawQuery": "SELECT gender FROM created_users LIMIT 5000"
    }
   ]
  },
  {
   "title": "Nationality Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawQuery": "SELECT nationality FROM created_users LIMIT 5000"
    }
   ]
  },
  {
   "title": "Recent Users (Limit 50)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawQuery": "SELECT first_name, last_name, email, gender, nationality, registered_date FROM created_users LIMIT 50"
    }
   ]
  }
 ]
}